(function(root){
 'use strict';
 const palettes={viridis_inverted:['#fde725','#7ad151','#22a884','#2a788e','#414487','#440154'],harvest:['#d73027','#fc8d59','#fee08b','#d9ef8b','#91cf60','#1a9850']};
 const defaults=()=>({palette:'viridis_inverted',colors:[...palettes.viridis_inverted],breaks:[120,130,140,160,180]});
 const valid=s=>s&&Object.hasOwn(palettes,s.palette)&&Array.isArray(s.colors)&&s.colors.length===6&&s.colors.every(c=>/^#[0-9a-f]{6}$/i.test(c))&&Array.isArray(s.breaks)&&s.breaks.length===5&&s.breaks.every((v,i)=>Number.isFinite(v)&&v>0&&v<1000000&&(!i||v>s.breaks[i-1]));
 const number=v=>Number(v).toLocaleString('pt-BR',{maximumFractionDigits:6});
 function labels(s){return s.breaks.map((v,i)=>(i?number(s.breaks[i-1]):'0')+(i===4?' a ':' a menos de ')+number(v)+' sc/ha').concat('Acima de '+number(s.breaks[4])+' sc/ha');}
 let settings=defaults(),revision=0,control,card,editor,list,toggle,paletteInput,rows,savedSelect,status,userId=null,authPromise,saved=[];const listeners=new Set();
 function category(value){const b=settings.breaks;return value<b[0]?0:value<b[1]?1:value<b[2]?2:value<b[3]?3:value<=b[4]?4:5;}
 function apply(next){if(!valid(next))throw new Error('Informe cinco limites positivos, em ordem crescente.');settings={palette:next.palette,colors:[...next.colors],breaks:[...next.breaks]};revision++;if(userId)try{root.localStorage.setItem('harvest-legend-v2:'+userId,JSON.stringify(settings));}catch{}render();listeners.forEach(fn=>fn());}
 async function identify(){
  if(authPromise)return authPromise;
  authPromise=(async()=>{if(!root.supabaseClient)return null;const {data,error}=await root.supabaseClient.auth.getUser();if(error||!data.user)return null;if(userId!==data.user.id){userId=data.user.id;let next=defaults();try{const pref=JSON.parse(root.localStorage.getItem('harvest-legend-v2:'+userId));if(valid(pref))next=pref;}catch{}apply(next);}return userId;})();try{return await authPromise;}finally{authPromise=null;}
 }
 async function listSaved(){if(!await identify())throw new Error('Entre na sua conta para recuperar suas legendas.');const {data,error}=await root.supabaseClient.from('harvest_user_legends').select('id,name,palette,breaks,colors').order('name');if(error)throw new Error('Não foi possível carregar suas legendas salvas.');saved=data;return data;}
 async function save(name,next){name=String(name||'').trim();if(!name||name.length>80)throw new Error('Dê um nome à legenda (até 80 caracteres).');if(!valid(next))throw new Error('Os limites precisam estar em ordem crescente.');if(!await identify())throw new Error('Entre na sua conta para salvar a legenda.');const {error}=await root.supabaseClient.from('harvest_user_legends').upsert({user_id:userId,name,palette:next.palette,breaks:next.breaks,colors:next.colors,updated_at:new Date().toISOString()},{onConflict:'user_id,name'});if(error)throw new Error('Não foi possível salvar a legenda na sua conta.');return name;}
 function render(){if(!list)return;list.replaceChildren();labels(settings).forEach((label,i)=>{const row=document.createElement('li'),dot=document.createElement('i'),text=document.createElement('span');dot.style.background=settings.colors[i];text.textContent=label;row.append(dot,text);list.append(row);});card.querySelector('.harvest-legend-ramp').style.background='linear-gradient(to right,'+settings.colors.join(',')+')';}
 function preview(){const b=rows.slice(0,5).map(r=>Number(r.limit.value));rows.forEach((row,i)=>{row.caption.textContent=i===5?'Acima de '+number(b[4])+' sc/ha':(i?number(b[i-1]):'0')+(i===4?' a':' a menos de');});}
 function fillEditor(){paletteInput.value=settings.palette;rows.forEach((row,i)=>{row.color.value=settings.colors[i];if(row.limit)row.limit.value=settings.breaks[i];});preview();}
 function readEditor(){return {palette:paletteInput.value,colors:rows.map(r=>r.color.value),breaks:rows.slice(0,5).map(r=>Number(r.limit.value))};}
 function close(){editor.hidden=true;toggle.setAttribute('aria-expanded','false');card.classList.remove('is-editing');}
 async function refreshSaved(){try{await listSaved();savedSelect.replaceChildren(new Option('Selecione uma legenda',''));saved.forEach(s=>savedSelect.add(new Option(s.name,s.id)));status.textContent=saved.length?'Suas legendas estão disponíveis nesta conta.':'Você ainda não salvou legendas.';}catch(error){status.textContent=error.message;}}
 function init(map){if(control)return;
  const Control=L.Control.extend({options:{position:'bottomright'},onAdd(){
   card=L.DomUtil.create('section','harvest-map-legend hidden');card.setAttribute('aria-label','Legenda da produtividade');
   card.innerHTML='<button type="button" class="harvest-legend-toggle" aria-expanded="false" aria-controls="harvest-legend-editor" aria-label="Editar legenda"><span><strong>Produtividade do milho</strong><small>sc/ha</small></span><i class="fa-solid fa-sliders" aria-hidden="true"></i></button><div class="harvest-legend-ramp"></div><ul class="harvest-classes"></ul><form id="harvest-legend-editor" class="harvest-legend-editor" hidden><label>Minhas legendas<select aria-label="Minhas legendas"><option value="">Selecione uma legenda</option></select></label><label>Rampa de cores<select aria-label="Rampa de cores"><option value="harvest">Vermelho a verde</option><option value="viridis_inverted">Viridis invertida</option></select></label><p>Altere os limites em sc/ha. Os textos são padronizados.</p><div class="harvest-legend-rows"></div><label class="harvest-legend-name">Nome para salvar<input type="text" maxlength="80" aria-label="Nome da legenda" placeholder="Ex.: Milho 2026"></label><button type="button" class="harvest-legend-save">Salvar na minha conta</button><p class="harvest-legend-status" role="status"></p><p class="harvest-legend-error" role="alert"></p><div class="harvest-legend-actions"><button type="button" data-action="reset">Restaurar</button><button type="button" data-action="cancel">Cancelar</button><button type="submit">Aplicar</button></div></form>';
   toggle=card.querySelector('.harvest-legend-toggle');editor=card.querySelector('form');list=card.querySelector('ul');paletteInput=editor.querySelector('[aria-label="Rampa de cores"]');savedSelect=editor.querySelector('[aria-label="Minhas legendas"]');status=editor.querySelector('[role="status"]');rows=[];
   const collapse=document.createElement('button');collapse.type='button';collapse.className='harvest-legend-collapse';
   function setCollapsed(collapsed){
    if(collapsed)close();
    card.classList.toggle('is-collapsed',collapsed);
    collapse.setAttribute('aria-expanded',String(!collapsed));
    collapse.setAttribute('aria-label',collapsed?'Expandir legenda da produtividade':'Recolher legenda da produtividade');
    collapse.textContent=collapsed?'Legenda · sc/ha ▴':'Recolher legenda ▾';
   }
   collapse.onclick=()=>setCollapsed(!card.classList.contains('is-collapsed'));
   card.prepend(collapse);setCollapsed(Boolean(root.matchMedia?.('(max-width: 820px)').matches));
   const container=editor.querySelector('.harvest-legend-rows');for(let i=0;i<6;i++){const row=document.createElement('div'),color=document.createElement('input'),caption=document.createElement('span');row.className='harvest-numeric-row';color.type='color';color.setAttribute('aria-label','Cor da faixa '+(i+1));row.append(color,caption);let limit=null;if(i<5){limit=document.createElement('input');limit.type='number';limit.min='0.000001';limit.max='999999';limit.step='any';limit.required=true;limit.setAttribute('aria-label','Limite da faixa '+(i+1));limit.oninput=preview;row.append(limit,document.createTextNode('sc/ha'));}container.append(row);rows.push({color,caption,limit});}
   toggle.onclick=()=>{if(editor.hidden){fillEditor();editor.hidden=false;card.classList.add('is-editing');toggle.setAttribute('aria-expanded','true');paletteInput.focus();refreshSaved();}else close();};
   paletteInput.onchange=()=>rows.forEach((r,i)=>{r.color.value=palettes[paletteInput.value][i];});
   savedSelect.onchange=()=>{const selected=saved.find(s=>s.id===savedSelect.value);if(selected){apply(selected);fillEditor();editor.querySelector('[aria-label="Nome da legenda"]').value=selected.name;status.textContent='Legenda carregada.';}};
   editor.onsubmit=e=>{e.preventDefault();try{apply(readEditor());editor.querySelector('[role="alert"]').textContent='';close();toggle.focus();}catch(error){editor.querySelector('[role="alert"]').textContent=error.message;}};
   editor.querySelector('.harvest-legend-save').onclick=async e=>{const button=e.currentTarget;button.disabled=true;try{const next=readEditor(),name=await save(editor.querySelector('[aria-label="Nome da legenda"]').value,next);apply(next);await refreshSaved();status.textContent='“'+name+'” salva na sua conta.';editor.querySelector('[role="alert"]').textContent='';}catch(error){editor.querySelector('[role="alert"]').textContent=error.message;}finally{button.disabled=false;}};
   editor.querySelector('[data-action="cancel"]').onclick=()=>{close();toggle.focus();};editor.querySelector('[data-action="reset"]').onclick=()=>{apply(defaults());fillEditor();};card.addEventListener('keydown',e=>{if(e.key==='Escape'){close();toggle.focus();}});L.DomEvent.disableClickPropagation(card);L.DomEvent.disableScrollPropagation(card);render();identify();return card;
  }});control=new Control().addTo(map);
 }
 root.HarvestStyle=Object.freeze({get:()=>({...settings,colors:[...settings.colors],breaks:[...settings.breaks],labels:labels(settings),revision}),category,color:v=>v==null?'#94a3b8':settings.colors[category(v)],apply,valid,labels,subscribe(fn){listeners.add(fn);return ()=>listeners.delete(fn);}});
 root.HarvestLegend=Object.freeze({init,save,listSaved,show(visible){if(card){card.classList.toggle('hidden',!visible);if(!visible)close();}}});
})(window);
